### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by ultraviolets369** [INFO-526-SU24/final-project-CristinaUAMS#1]
The following is the peer review of the project proposal by Violeta Keifer. The team members that participated in this review are :

- [Violeta Keifer] - @[ultraviolets369]

- Describe the goal of the project.
The goal of the project is to determine if people who participated in the Great American Coffee Survey can correctly determine the acidity and bitterness of coffee and see if this judgement is affected by preference of four coffee samples. The second goal is to see if political affiliation is correlated to preference in coffee. 

- Describe the data used or collected.
Data from the Great American Coffee Survey on Tidy Tuesday and data from a review of acids in coffee by Yeager et al. The data from the acidity review will be compared to the rating of acidity of different brews by participants in the survey. Both have coffees sorted by type of roast.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
For the first question, the data from the survey and the acid review by Yeager et al will be combined into one table and compared by roast level. They will also look at the correlation between participants ability to correctly guess acidity and how much they liked the coffee.

For the second question, they will examine the political affiliation of participants and group this by which coffee people preferred.

- Is there anything that is unclear from the proposal?

The proposal is clear and has all the necessary parts. I appreciated the extra touches of images of coffee makers, the graphs they will use from Yeager et al., and customization of the table. 

- Provide constructive feedback on how the team might be able to improve their project.

I would like to know what kind of graphs/particular methods that will be used to answer each of their questions. I am also curious if the data from Yeager et al will need to be tidied or summarized before being used.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.

I am most interested to see how the data they pulled in from the Yeager et al. study will compare to the coffee survey. This extra data will provide extra context about the acidity of the coffee samples.

- Provide constructive feedback on any issues with file and/or code organization.
Files are organized well. Images are all in the image folder, data is in the data folder, and everything rendered locally properly.

- (Optional) Any further comments or feedback?

**Comment by CristinaUAMS** [comment]
Thank you for your thoughtful feedback! I added what I  thought will be the best way to visualize the data and made sure to highlight the ways in which I will have to tidy up the additional data I will be using!

Best regards!
