### ISSUE TITLE
Proposal peer review

### ISSUE THREAD

**Issue by cwjohn13** [INFO-526-SU24/final-project-CristinaUAMS#2]
The following is the peer review of the project proposal by Cole Johnson - cwjohn13

- Describe the goal of the project.
There are 2 goals of this project, the first goal is to determine if people tend to quantify acidity and bitterness in coffee correctly and to determine if their preference in coffee effects their ability to to judge acidity and bitterness.
The second goal is to determine if political affiliation plays a part in coffee preference.

- Describe the data used or collected.
There is data collected from a coffee taste test held on youtube which contains 4042 responses to survey questions.
There is also supporting data collected that will give definitive analysis on acidity in coffee by roast and a source for what causes bitterness and acidity in taste.

- Describe how the research question will be answered, e.g. what approaches / methods will be used.
the first question will be answered by joining all 3 datasets by the roast variable, and 2 new variables will be created for total relevant organic acids and total relevant CGAs. These new variables will be compared by roast alongside what the survey responses believed to be acidic and non acidic. This result will then be compared to their favorite coffee beverage to gain insights on if their favorite coffee beverage effects their ability to quantify acidity and bitterness correctly.
The second question will be answered by examining political affiliation alongside their preferred coffees.

- Is there anything that is unclear from the proposal?
I would describe the 2 extra data sets a bit more, I dont know too much about coffee so I had to look up what chlorogenic acids were, maybe a slight description of that would be nice. 

- Provide constructive feedback on how the team might be able to improve their project.
It looks like you are doing this project as an individual and not a team. I am pretty certain you are only required 1 question and to make 2 plots answering that 1 question. I would focus your time on your first question, it seems like there is a lot of good info there and remove your second question from the project.
Maybe make that first question a little more broad so that you can have 2 good plots both giving insights:
for example something like "is coffee preference or age a better indication of how correct people tend to be when quantifying acidity and bitterness in coffee?" 
That isn't necessarily a good question but I think it gets the point, you can again 2 different insights from the same question.

- What aspect of this project are you most interested in and would like to see highlighted in the presentation.
I am interested in your insights gained from question 1, and if those who prefer darker roasts will be not be able to quantify acidity or bitterness as well.

- Provide constructive feedback on any issues with file and/or code organization.
Only thing that really stuck out to me was the figure "AcidLevelByRoast" was low resolution, it is very difficult to read any of the legends. Maybe write a statement describing that visualization?

- (Optional) Any further comments or feedback?
Overall looks really good!

**Comment by CristinaUAMS** [comment]
Thank you so much for your thought provoking feedback! I have added descriptions to the chart I included from the journal article as well as some additional information describing the data collected from it. I like having the two different questions (especially since the second is going to be much more simple to answer). But I also like your idea of perhaps broadening my first question. I have not done that at this time but am keeping the suggestion in mind going forward such that if I see an opportunity to broaden what I look at, I might do so. 

Thanks again!

Best regards!
